### Create report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "Toyota",
    "model": "Camry",
    "year": 2020,
    "mileage": 15000,
    "lng": 105.85,
    "lat": 21.02,
    "price": 20000
}

### Approve report
PATCH http://localhost:3000/reports/1/approval
content-type: application/json

{
    "approved": true
}

### Get all reports
GET http://localhost:3000/reports?page=1&limit=10
content-type: application/json

### Get a report by id
GET http://localhost:3000/reports/2
content-type: application/json

### Update a report by id
PATCH http://localhost:3000/reports/1
content-type: application/json

{
    "make": "Toyota",
    "model": "Camry",
    "year": 2020,
    "mileage": 15000,
    "lng": 105.85,
    "lat": 21.02,
    "price": 20000
}

### Delete a report by id
DELETE http://localhost:3000/reports/1
content-type: application/json