@root=http://localhost:3000/api/v1


### Create report
POST {{root}}/reports
content-type: application/json

{
    "make": "Toyota",
    "model": "Camry",
    "year": 2020,
    "mileage": 12000,
    "lng": 105.85,
    "lat": 21.02,
    "price": 2400000
}

### Approve report
PATCH {{root}}/reports/18/approval
content-type: application/json

{
    "approved": true
}

### Get estimate
GET {{root}}/reports/estimate?make=Toyota&model=Camry&year=2020&mileage=12000&lng=105.85&lat=21.02
content-type: application/json

### Get all reports
GET {{root}}/reports?page=1&limit=10
content-type: application/json

### Get a report by id
GET {{root}}/reports/2
content-type: application/json

### Update a report by id
PATCH {{root}}/reports/1
content-type: application/json

{
    "make": "Toyota",
    "model": "Camry",
    "year": 2020,
    "mileage": 15000,
    "lng": 105.85,
    "lat": 21.02,
    "price": 20000
}

### Delete a report by id
DELETE {{root}}/reports/8
content-type: application/json