@root=http://localhost:3000/api/v1

### Create user
POST {{root}}/users
content-type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "abc123@"
}

### Get all users
GET {{root}}/users?page=1&limit=10&email=
content-type: application/json

### Get a user by id
GET {{root}}/users/2
content-type: application/json

### Update a user by id
PATCH {{root}}/users/1
content-type: application/json

{
    "name": "Jane Doe 2s",
    "email": "jane2doe@example.com"
}

### Delete a user by id
DELETE {{root}}/users/5
content-type: application/json
